### ISSUE TITLE
Error while Installing go modules

### ISSUE THREAD

**Issue by raphaelbernhart** [ez4o/github-contribution-graph#1]
Hello there :)

when I am installing the go modules with `go get -u` I get the error:
```
go: server@v0.0.0 requires
        model@v0.0.0: malformed module path "model": missing dot in first path element
```

As I am not developing with go (atm) I don't know what to do with this error. I looked for a missing dot in the files but found none. As debugging the error I found out that the error msg changed when removing the replaces from the `./src/server/go.mod` file...maybe this has smthn to do with the error?

Thanks for helping/fixing the error

**Comment by wst24365888** [comment]
Hi, what's your Go version? You can check it with `go version`.

**Comment by raphaelbernhart** [comment]
> 

`go version go1.15.5 darwin/amd64`

**Comment by wst24365888** [comment]
Actually, I've never encountered this problem before, and both of my computers are working fine with Go `1.17.5`. 

I think that's probably because of some incompatibility with Go `1.15.5`, maybe try: 

1. Upgrade Go version to `1.17.x`
2. `go mod tidy -compat="1.17"`
3. `go get -u`

Go module is always changing, and I think it's really confusing between different versions. 😢

**Comment by wst24365888** [comment]
@raphaelbernhart Hello there, any updates on this issue? 
I've tested the above solution and it should work. :D
